<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PhonesEmails value colomn_CellTextBox</name>
   <tag></tag>
   <elementGuidId>22332985-243f-4c0c-a0d0-99566dd4432c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.z-CellTextBox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[contains(@class,'z-CellTextBox')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0f06c104-b937-436a-9b46-9a050c2a62b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-CellTextBox</value>
      <webElementGuid>289616f4-945c-457c-9afd-548ede8e9715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>06840358-2ec7-417b-945e-6310ee07ed00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0541231234</value>
      <webElementGuid>b5f9b413-5cae-4f98-ac7f-a9080ef0a7f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>c5078840-7bd1-495f-8bbf-e94a238bde5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;z-RootPanel z-ApplicationLoggedIn&quot;]/div[@class=&quot;z-WorkspaceHolder&quot;]/div[2]/div[@class=&quot;z-FlowHorizontalPanel&quot;]/div[@class=&quot;z-FlowVerticalPanel&quot;]/div[2]/div[@class=&quot;gwt-SplitLayoutPanel&quot;]/div[4]/div[@class=&quot;z-DataView z-DataView-Selected&quot;]/div[2]/div[1]/div[3]/div[@class=&quot;z-ScrollPage z-Workspace&quot;]/div[@class=&quot;z-Scroll&quot;]/div[1]/div[@class=&quot;z-FlowVerticalPanel z-RoundedPanelFullWidth&quot;]/div[@class=&quot;z-FlowVerticalPanel&quot;]/div[@class=&quot;z-FlowVerticalPanel&quot;]/div[2]/div[@class=&quot;z-FlowVerticalPanel noWrap zrl-FlexVertical&quot;]/div[@class=&quot;z-FlowVerticalPanel&quot;]/div[@class=&quot;z-FlowVerticalPanel&quot;]/div[@class=&quot;z-FlowVerticalPanel&quot;]/div[@class=&quot;dataGridWidget z-DataGrid z-Phone-Editor&quot;]/div[3]/div[@class=&quot;GKIQDVXMH&quot;]/div[2]/div[1]/div[@class=&quot;GKIQDVXH&quot;]/table[1]/tbody[1]/tr[@class=&quot;dataGridEvenRow dataGridHoveredRow dataGridKeyboardSelectedRow&quot;]/td[@class=&quot;dataGridCell dataGridEvenRowCell dataGridHoveredRowCell dataGridKeyboardSelectedRowCell dataGridKeyboardSelectedCell&quot;]/div[1]/input[@class=&quot;z-CellTextBox&quot;]</value>
      <webElementGuid>a72cefe7-1d35-40bc-9544-4eca4de99aa5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='0541231234']</value>
      <webElementGuid>ac66dcc1-42ae-45f4-bdde-4e8712450ac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/input</value>
      <webElementGuid>d06f4d28-ff9c-47c5-b6eb-d5b6f85ec6bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>4636de38-6d94-4ad0-bbab-d83cf1a3068d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
