<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SearchPerson_Button</name>
   <tag></tag>
   <elementGuidId>aba5a261-a739-4a9b-b178-93095dc5bf6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.z-ImageButton-Image.z-AttachIcon-Image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d75a4d13-089d-4d50-8590-68743efd4fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>system/icons/search_patient.png</value>
      <webElementGuid>7ca188de-b90d-42d0-ba5e-93b6fb73cfef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-ImageButton-Image z-AttachIcon-Image</value>
      <webElementGuid>8c7f1d57-c088-4b01-9ecb-8b70d7daa799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;z-RootPanel z-ApplicationLoggedIn&quot;]/div[@class=&quot;z-WorkspaceHolder&quot;]/div[2]/div[@class=&quot;z-FlowHorizontalPanel&quot;]/div[@class=&quot;z-FlowVerticalPanel&quot;]/div[2]/div[@class=&quot;gwt-SplitLayoutPanel&quot;]/div[4]/div[@class=&quot;z-DataView z-DataView-Selected&quot;]/div[@class=&quot;z-DataViewBgColor&quot;]/div[@class=&quot;z-FlowVerticalPanel&quot;]/div[@class=&quot;z-FlowVerticalPanel&quot;]/div[2]/div[@class=&quot;z-FlowVerticalPanel z-RoundedPanelFullWidth&quot;]/div[@class=&quot;z-FlowHorizontalPanel&quot;]/div[@class=&quot;z-FlowVerticalPanelWithTitle&quot;]/div[@class=&quot;z-FlowHorizontalPanel&quot;]/div[@class=&quot;z-ImageButton z-AttachIcon z-ImageButton-down&quot;]/img[@class=&quot;z-ImageButton-Image z-AttachIcon-Image&quot;]</value>
      <webElementGuid>afd2daac-75b7-481d-abbd-307cf28b3047</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/img</value>
      <webElementGuid>b9274e0b-8956-4eaa-b659-4c60d66f84e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'system/icons/search_patient.png']</value>
      <webElementGuid>ccb41663-823d-4a39-8ae7-7848d3019a16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
