<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Student Number After saving in the table</name>
   <tag></tag>
   <elementGuidId>98404f9a-31a4-4415-919f-a7fc5375d900</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.dataGridCell.dataGridEvenRowCell.dataGridFirstColumn.dataGridHoveredRowCell > div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@__gwt_cell = 'cell-gwt-uid-331']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tbody/tr[1]/td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9daa7812-0bb1-4f83-8fe2-376d280bab93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>__gwt_cell</name>
      <type>Main</type>
      <value>cell-gwt-uid-331</value>
      <webElementGuid>00b3fae2-ea87-4900-be3d-06a59fe46add</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>T000182689</value>
      <webElementGuid>96c71599-93e1-4a1f-8a81-05749d85c43c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;z-RootPanel z-ApplicationLoggedIn&quot;]/div[@class=&quot;z-WorkspaceHolder&quot;]/div[2]/div[@class=&quot;z-FlowHorizontalPanel&quot;]/div[@class=&quot;z-FlowVerticalPanel&quot;]/div[2]/div[@class=&quot;gwt-SplitLayoutPanel&quot;]/div[4]/div[@class=&quot;z-DataView z-DataView-Selected&quot;]/div[2]/div[1]/div[3]/div[@class=&quot;z-FlowVerticalPanel z-Workspace&quot;]/div[@class=&quot;z-PatientSearchEditor&quot;]/div[@class=&quot;z-RoundedPanelFullWidth&quot;]/div[@class=&quot;dataGridWidget z-DataGrid&quot;]/div[3]/div[@class=&quot;GKIQDVXMH&quot;]/div[2]/div[1]/div[@class=&quot;GKIQDVXH&quot;]/table[1]/tbody[1]/tr[@class=&quot;dataGridEvenRow dataGridHoveredRow&quot;]/td[@class=&quot;dataGridCell dataGridEvenRowCell dataGridFirstColumn dataGridHoveredRowCell&quot;]/div[1]</value>
      <webElementGuid>2d21595e-f0fc-43a7-9bd6-83ac12e997d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phones'])[1]/following::div[16]</value>
      <webElementGuid>6f840e00-ef08-4783-bbe8-45569575ebb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Birth Date'])[1]/following::div[16]</value>
      <webElementGuid>21365f99-f824-42a7-8068-692a08cb9497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mahmoud Hammad'])[1]/preceding::div[2]</value>
      <webElementGuid>a55de54e-bb55-43dc-b7ff-faf019a4b9ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='T000182689']/parent::*</value>
      <webElementGuid>4f6b7dd3-e554-42e9-b47e-8a4c1aa07e4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div</value>
      <webElementGuid>456dc2fb-4e3b-4d09-928e-c17e63b43229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'T000182689' or . = 'T000182689')]</value>
      <webElementGuid>5362f9bc-35ad-4bde-83d0-1330994f1970</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
