<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Site_List</name>
   <tag></tag>
   <elementGuidId>34473dfa-1602-46e4-a7a3-ee3fec710bb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[4]/select</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d2dcf2d5-4a04-4898-ae2a-c75eeed53e5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-ListBox</value>
      <webElementGuid>0c42883f-a172-4c80-b8d7-72034149da60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>General Authority of Islamic Affairs &amp; EndowmentIATMINISTRY OF EDUCATIONMINISTRY OF EDUCATION - PVTMINISTRY OF EDUCATION-ASSPMINISTRY OF EDUCATION-CEMINISTRY OF EDUCATION-POD centers</value>
      <webElementGuid>af41ca2b-b330-45ea-a6f2-d1a4dc82fe2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;z-RootPanel z-ApplicationLoggedOut&quot;]/div[@class=&quot;z-DialogBox fadeIn&quot;]/div[1]/table[1]/tbody[1]/tr[@class=&quot;dialogMiddle&quot;]/td[@class=&quot;dialogMiddleCenter&quot;]/div[@class=&quot;dialogMiddleCenterInner dialogContent&quot;]/div[@class=&quot;z-FlowVerticalPanel GKIQDVXGCB z-DialogBoxContent&quot;]/div[@class=&quot;z-FlowHorizontalPanel GKIQDVXFCB&quot;]/select[@class=&quot;z-ListBox&quot;]</value>
      <webElementGuid>b4a577e1-8717-4719-8a19-dd5c012e4245</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/select</value>
      <webElementGuid>c7236ce1-addf-40fd-bbdd-edc577082718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = 'General Authority of Islamic Affairs &amp; EndowmentIATMINISTRY OF EDUCATIONMINISTRY OF EDUCATION - PVTMINISTRY OF EDUCATION-ASSPMINISTRY OF EDUCATION-CEMINISTRY OF EDUCATION-POD centers' or . = 'General Authority of Islamic Affairs &amp; EndowmentIATMINISTRY OF EDUCATIONMINISTRY OF EDUCATION - PVTMINISTRY OF EDUCATION-ASSPMINISTRY OF EDUCATION-CEMINISTRY OF EDUCATION-POD centers')]</value>
      <webElementGuid>ec435c5a-29b5-49f7-a59a-0dd9a1a8dc04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
