<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Student Details close(x)_Button</name>
   <tag></tag>
   <elementGuidId>7ff79ebf-d002-4a60-99eb-8c972a83636f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.z-FlowHorizontalPanel.z-NavigationPanelTab.z-NavigationPanelTab-selected > img.z-NavigationPanelTabImage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d54a6dab-2750-430e-b6d2-5494039cee2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>system/icons/close_round.png</value>
      <webElementGuid>1452f936-bbc0-4d5d-8e35-21039bc99780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-NavigationPanelTabImage</value>
      <webElementGuid>5a4e0572-602f-4a33-8109-963486f052fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;z-RootPanel z-ApplicationLoggedIn&quot;]/div[@class=&quot;z-WorkspaceHolder&quot;]/div[2]/div[@class=&quot;z-FlowHorizontalPanel&quot;]/div[@class=&quot;z-FlowVerticalPanel&quot;]/div[@class=&quot;z-FlowVerticalPanel z-NavigationPanel&quot;]/div[@class=&quot;gwt-TabLayoutPanel&quot;]/div[2]/div[@class=&quot;z-FlowHorizontalPanel z-NavigationPanelTabBorder&quot;]/div[@class=&quot;z-FlowHorizontalPanel z-ScrollableTabPanel&quot;]/div[@class=&quot;z-FlowHorizontalPanel z-ScrollableTab&quot;]/div[@class=&quot;gwt-TabLayoutPanelTabs z-ScrollableTabs&quot;]/div[@class=&quot;gwt-TabLayoutPanelTab GKIQDVXH gwt-TabLayoutPanelTab-selected&quot;]/div[@class=&quot;gwt-TabLayoutPanelTabInner&quot;]/div[@class=&quot;z-FlowHorizontalPanel z-NavigationPanelTab z-NavigationPanelTab-selected&quot;]/img[@class=&quot;z-NavigationPanelTabImage&quot;]</value>
      <webElementGuid>1430148f-c117-4e62-ab62-80aeaf81aec3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/img</value>
      <webElementGuid>86df2700-6e5e-4ae6-962c-e304a9358bc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'system/icons/close_round.png']</value>
      <webElementGuid>85166d65-c4fb-4b7e-ba71-72b15cd5364a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
