<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Download Attachment1_Button</name>
   <tag></tag>
   <elementGuidId>b498de28-381d-438c-9ec9-d848ceb50483</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.gwt-Image.z-ImageButton.z-AttachIcon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[5]/div[1]/table[1]/tbody[1]/tr[2]/td[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[4]/div[1]/div[2]/table[1]/tbody[1]/tr[1]/td[2]/div[1]/img[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>28a7bcbc-ca45-4c26-98a4-2ed204c1b137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>system/icons/download.png</value>
      <webElementGuid>aa0fbc65-3449-479b-9adb-5fe9c37acfd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gwt-Image z-ImageButton z-AttachIcon</value>
      <webElementGuid>0f727a8b-ae8e-46e8-967c-79d5595514f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;z-RootPanel z-ApplicationLoggedIn&quot;]/div[@class=&quot;z-DialogBox fadeIn&quot;]/div[1]/table[1]/tbody[1]/tr[@class=&quot;dialogMiddle&quot;]/td[@class=&quot;dialogMiddleCenter&quot;]/div[@class=&quot;dialogMiddleCenterInner dialogContent&quot;]/div[@class=&quot;z-DialogBoxContent&quot;]/div[1]/div[@class=&quot;z-FlowVerticalPanel&quot;]/div[@class=&quot;z-FlowVerticalPanel&quot;]/div[@class=&quot;z-ScrollPage&quot;]/div[@class=&quot;z-Scroll&quot;]/div[1]/div[@class=&quot;z-FlowVerticalPanel z-Panel&quot;]/div[1]/div[@class=&quot;z-FlowVerticalPanel&quot;]/div[@class=&quot;z-FlowVerticalPanel z-Margin-Top-10 z-AddMargin z-MandatoryLabel&quot;]/div[@class=&quot;z-FlowVerticalPanel z-MandatoryAttribute&quot;]/div[@class=&quot;z-FlowVerticalPanel&quot;]/table[@class=&quot;cellTableWidget z-CellTable&quot;]/tbody[1]/tr[@class=&quot;cellTableEvenRow z-CellTableRowEven cellTableHoveredRow&quot;]/td[@class=&quot;cellTableCell cellTableEvenRowCell cellTableHoveredRowCell&quot;]/div[1]/img[@class=&quot;gwt-Image z-ImageButton z-AttachIcon&quot;]</value>
      <webElementGuid>5b11b897-00e2-4118-b436-3c8a2c57ef0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/img</value>
      <webElementGuid>5c2f7072-c55a-4c18-a854-69fcbb3e0f6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'system/icons/download.png']</value>
      <webElementGuid>d14337cd-0dd6-4342-9c92-aabe2fee6155</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
