<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>8-3-1980</name>
   <tag></tag>
   <elementGuidId>ed83830d-f65d-42a3-8fc4-ea322025ed82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(3) > td:nth-of-type(7) > div.datePickerDay.datePickerDayIsWeekend</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[2]/following::div[14]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f806bf0d-b956-4819-916a-33dc30b210fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f95cd77e-0af1-43a2-b296-49701823f857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1ea04c4a-4c32-4525-98c8-f92561b397fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datePickerDay datePickerDayIsWeekend </value>
      <webElementGuid>4723c0ed-fd8d-44fe-b479-e5e140e0d969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>352b200a-3fbb-4537-a3bd-f9e1fd46f84f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;z-RootPanel z-ApplicationLoggedIn&quot;]/div[@class=&quot;dateBoxPopup z-IndexTopMost&quot;]/div[@class=&quot;popupContent&quot;]/table[@class=&quot;gwt-DatePicker&quot;]/tbody[1]/tr[2]/td[1]/table[@class=&quot;datePickerDays&quot;]/tbody[1]/tr[3]/td[7]/div[@class=&quot;datePickerDay datePickerDayIsWeekend&quot;]</value>
      <webElementGuid>0a4c6b89-4e1c-4b0e-bd83-1e07fb03e06b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[2]/following::div[14]</value>
      <webElementGuid>615fadce-53af-426b-b2c0-a845099cd58e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F'])[2]/following::div[14]</value>
      <webElementGuid>aad27465-307b-4270-b045-cfd6d7936128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='8']/parent::*</value>
      <webElementGuid>a9931f6d-24f9-40d7-a476-be0c216ddc29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[7]/div</value>
      <webElementGuid>46888a26-2d94-44c8-91c0-f698cd791a9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '8' or . = '8')]</value>
      <webElementGuid>85563cd3-d34a-4b1f-9809-ab499c90fc36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
